// Restaurant Data for Celiac Safe Finder
// Note: This data requires verification. Ratings and certifications should be validated.

export const getRestaurantImage = (keywords) => {
    const k = keywords.toLowerCase();
    if(k.includes('beach') || k.includes('ocean')) return 'https://images.unsplash.com/photo-1571896349842-68cfd429d052?q=80&w=1000';
    if(k.includes('mountain') || k.includes('alpine')) return 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=1000';
    if(k.includes('city') || k.includes('london') || k.includes('york')) return 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1000';
    if(k.includes('italy') || k.includes('pasta')) return 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1000';
    if(k.includes('jungle') || k.includes('green')) return 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000';
    return 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1000';
};

export const restaurants = [
    { id: 1, name: "Anamaya Resort", lat: 9.6558, lng: -85.0609, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Montezuma, Costa Rica", vibe: "Jungle / Yoga Retreat", price: "$$", website: "https://anamaya.com", desc: "100% Gluten-Free premises. Organic farm-to-table.", badges: ["100% GF", "Organic"], verified: true },
    { id: 2, name: "Gwinganna Lifestyle Retreat", lat: -28.2166, lng: 153.3833, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Queensland, Australia", vibe: "Wellness / Eco-Luxury", price: "$$$", website: "https://www.gwinganna.com", desc: "Entire property is GF and Dairy Free. No cross-contamination.", badges: ["GF & DF", "Eco"], verified: true },
    { id: 3, name: "The Inn Berlin", lat: 38.3287, lng: -75.0849, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Maryland, USA", vibe: "Historic / Charming", price: "$$", website: "https://theinnberlin.com", desc: "100% Gluten-Free Bed & Breakfast.", badges: ["B&B", "Historic"], verified: false },
    { id: 4, name: "The Riverside Inn", lat: 44.2965, lng: -71.7676, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "New Hampshire, USA", vibe: "Cozy / Nature", price: "$$", website: "https://www.riversidehotelnh.com", desc: "First 100% GF B&B in New England.", badges: ["100% GF", "Nature"], verified: false },
    { id: 5, name: "Gasthaus Bischenberg", lat: 48.4552, lng: 8.0468, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Black Forest, Germany", vibe: "Rustic / Nature", price: "$$", website: "https://www.gasthaus-bischenberg.de", desc: "100% Dedicated Gluten-Free Hotel & Restaurant.", badges: ["Dedicated Hotel", "Rustic"], verified: true },
    { id: 6, name: "Hotel Auberge La Fenière", lat: 43.7384, lng: 5.3787, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Provence, France", vibe: "Culinary / Luxury", price: "$$$", website: "https://www.aubergelafeniere.com", desc: "Chef Nadia Sammut runs a 100% GF Michelin Star kitchen.", badges: ["Michelin Star", "100% GF"], verified: true },
    { id: 7, name: "Hotel Drumlerhof", lat: 46.9175, lng: 11.9568, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "South Tyrol, Italy", vibe: "Alpine Wellness", price: "$$$", website: "https://www.drumlerhof.com", desc: "AIC Certified. Owned by Celiac family. Dedicated areas.", badges: ["AIC Certified", "Spa"], verified: true },
    { id: 8, name: "Hotel Villa Madonna", lat: 46.5639, lng: 11.5833, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Dolomites, Italy", vibe: "Family / Mountain", price: "$$", website: "https://www.villamadonna.it", desc: "AIC Certified. Kitchen divided; specialist staff.", badges: ["AIC Certified", "Family"], verified: true },
    { id: 9, name: "Arenas del Mar", lat: 9.3949, lng: -84.1539, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Manuel Antonio, Costa Rica", vibe: "Rainforest Luxury", price: "$$$", website: "https://www.arenasdelmar.com", desc: "Certified by Celiac Assoc. Dedicated prep area.", badges: ["Certified", "Beachfront"], verified: false },
    { id: 10, name: "Grand Velas Riviera Maya", lat: 20.6669, lng: -87.0372, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Riviera Maya, Mexico", vibe: "Ultra-Luxury All-Inclusive", price: "$$$$", website: "https://rivieramaya.grandvelas.com", desc: "Dedicated allergy-free preparation rooms. Concierge protocol.", badges: ["All-Inclusive", "Protocol"], verified: false },
    { id: 11, name: "Playa Garden Selection Hotel", lat: 39.8059, lng: 3.1203, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Mallorca, Spain", vibe: "Family Beach Resort", price: "$$", website: "https://www.gardenhotels.com", desc: "FACE Certified. Color-coded crockery & dedicated buffet.", badges: ["FACE Certified", "Family"], verified: true },
    { id: 12, name: "Alcudia Garden Aparthotel", lat: 39.8415, lng: 3.1256, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Mallorca, Spain", vibe: "Family / Apartment", price: "$", website: "https://www.gardenhotels.com", desc: "FACE Certified protocols.", badges: ["FACE Certified", "Apartments"], verified: true },
    { id: 13, name: "The Maynard", lat: 53.3073, lng: -1.6377, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Peak District, UK", vibe: "Countryside Boutique", price: "$$", website: "https://www.themaynard.com", desc: "Coeliac UK Accredited.", badges: ["Accredited", "Boutique"], verified: true },
    { id: 14, name: "Vitality Hotel Punta", lat: 44.5230, lng: 14.4716, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Losinj, Croatia", vibe: "Wellness / Island", price: "$$$", website: "https://www.losinj-hotels.com", desc: "First certified GF hotel in Croatia.", badges: ["Certified", "Wellness"], verified: true },
    { id: 15, name: "Avra Imperial Hotel", lat: 35.5303, lng: 23.7744, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Crete, Greece", vibe: "Modern Luxury", price: "$$$", website: "https://www.avraimperialhotel.gr", desc: "Verified GF protocols; Award winner.", badges: ["Award Winning", "Luxury"], verified: false },
    { id: 16, name: "Kamalaya", lat: 9.4286, lng: 99.9863, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Koh Samui, Thailand", vibe: "Spiritual Wellness", price: "$$$", website: "https://www.kamalaya.com", desc: "Wellness sanctuary with separate 'Detox' kitchen protocols.", badges: ["Detox", "Wellness"], verified: false },
    { id: 17, name: "Chiva-Som", lat: 12.5350, lng: 99.9620, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Hua Hin, Thailand", vibe: "Medical Wellness", price: "$$$$", website: "https://www.chivasom.com", desc: "Medical wellness; strict personalized diets.", badges: ["Medical", "Personalized"], verified: false },
    { id: 18, name: "Sandals Grenada", lat: 12.0125, lng: -61.7690, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "St. George's, Grenada", vibe: "Couples / Romantic", price: "$$$", website: "https://www.sandals.com", desc: "Culinary Concierge desk; strictly separate prep.", badges: ["Adults Only", "Concierge"], verified: false },
    { id: 19, name: "El Dorado Maroma", lat: 20.7388, lng: -86.9686, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Riviera Maya, Mexico", vibe: "Romantic / Adults Only", price: "$$$", website: "https://www.karismahotels.com", desc: "Gourmet Inclusive caters to allergies with separate prep.", badges: ["Gourmet", "Romantic"], verified: false },
    { id: 20, name: "Hotel Alexander", lat: 45.5979, lng: 12.8687, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Caorle, Italy", vibe: "Seaside Resort", price: "$$", website: "https://www.hotelalexander.net", desc: "AIC Certified.", badges: ["AIC Certified", "Seaside"], verified: true },
    { id: 21, name: "Hotel Sanremo", lat: 45.6015, lng: 12.8805, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Caorle, Italy", vibe: "Beachfront", price: "$$", website: "https://www.hotelsanremocaorle.it", desc: "AIC Certified.", badges: ["AIC Certified", "Beach"], verified: true },
    { id: 22, name: "Grand Hotel Molveno", lat: 46.1430, lng: 10.9659, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Molveno, Italy", vibe: "Lakeside", price: "$$", website: "https://www.grandhotelmolveno.it", desc: "AIC Certified.", badges: ["AIC Certified", "Lakeside"], verified: true },
    { id: 23, name: "Eden Hotel", lat: 45.7176, lng: 10.7836, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Lake Garda, Italy", vibe: "Italian Lakes", price: "$$", website: "https://www.eden-hotel.it", desc: "AIC Certified.", badges: ["AIC Certified", "Lake View"], verified: true },
    { id: 24, name: "Parador de Cangas de Onís", lat: 43.3643, lng: -5.1386, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Asturias, Spain", vibe: "Historic Monastery", price: "$$", website: "https://www.parador.es", desc: "Paradores group has strict FACE agreement.", badges: ["FACE Agreement", "Historic"], verified: true },
    { id: 25, name: "Goldener Adler", lat: 47.0114, lng: 10.2906, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Ischgl, Austria", vibe: "Ski / Mountain", price: "$$$", website: "https://www.goldener-adler.at", desc: "Marketed as 'Celiac Hotel' with separate cuisine.", badges: ["Skiing", "Dedicated Cuisine"], verified: false },
    { id: 26, name: "Relais Bourgondisch Cruyce", lat: 51.2066, lng: 3.2268, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Bruges, Belgium", vibe: "Historic Boutique", price: "$$$", website: "https://www.relaisbourgondischcruyce.be", desc: "Known for accommodating severe celiacs.", badges: ["Boutique", "Celiac Safe"], verified: false },
    { id: 27, name: "Hotel Gutenberg", lat: 46.6806, lng: 11.2335, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "South Tyrol, Italy", vibe: "Family / Nature", price: "$$", website: "https://www.hotelgutenberg.eu", desc: "Certified by TÜV NORD for allergy safety.", badges: ["TÜV Certified", "Family"], verified: true },
    { id: 28, name: "Como Shambhala Estate", lat: -8.4357, lng: 115.2475, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Bali, Indonesia", vibe: "Jungle Luxury", price: "$$$$", website: "https://www.comohotels.com", desc: "High-end wellness with strict dietary separation.", badges: ["High-End", "Wellness"], verified: false },
    { id: 29, name: "Eichardt's Private Hotel", lat: -45.0312, lng: 168.6626, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Queenstown, New Zealand", vibe: "Lakefront Luxury", price: "$$$$", website: "https://www.eichardts.com", desc: "Boutique nature allows personal chef separation.", badges: ["Private Chef", "Luxury"], verified: false },
    { id: 30, name: "MSC Cruises", lat: 38.0, lng: 16.0, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Mediterranean Sea", vibe: "Cruise", price: "$", website: "https://www.msccruises.com", desc: "Partnership with AIC. Sealed GF galley room.", badges: ["Cruise", "AIC Partner"], verified: true },
    { id: 31, name: "AmaWaterways", lat: 47.4979, lng: 19.0402, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Danube River, Europe", vibe: "River Cruise", price: "$$$", website: "https://www.amawaterways.com", desc: "Highly trained; often host GF sailing weeks.", badges: ["River Cruise", "Trained"], verified: false },
    { id: 32, name: "Hotel Club Saraceno", lat: 39.9238, lng: 9.6873, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Sardinia, Italy", vibe: "Beach Resort", price: "$$", website: "https://www.hotelclubsaraceno.com", desc: "AIC Certified.", badges: ["AIC Certified", "Resort"], verified: true },
    { id: 33, name: "Park Hotel Marinetta", lat: 43.2384, lng: 10.5367, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Tuscany, Italy", vibe: "Coastal Tuscany", price: "$$$", website: "https://www.hotelmarinetta.it", desc: "AIC Certified.", badges: ["AIC Certified", "Coastal"], verified: true },
    { id: 34, name: "Hotel Bristol Buja", lat: 45.3533, lng: 11.7854, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Abano Terme, Italy", vibe: "Thermal Spa", price: "$$$", website: "https://www.bristolbuja.it", desc: "AIC Certified.", badges: ["AIC Certified", "Thermal"], verified: true },
    { id: 35, name: "Hotel Relais Des Glaciers", lat: 45.8456, lng: 7.7346, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Aosta, Italy", vibe: "Alpine / Ski", price: "$$", website: "https://www.hotelrelaisdesglaciers.com", desc: "AIC Certified.", badges: ["AIC Certified", "Ski"], verified: true },
    { id: 36, name: "Grand Hotel Dino", lat: 45.8973, lng: 8.5393, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Lake Maggiore, Italy", vibe: "Grand Lake Hotel", price: "$$$", website: "https://www.zaccherahotels.com", desc: "AIC Certified.", badges: ["AIC Certified", "Grand"], verified: true },
    { id: 37, name: "Hotel Minerva", lat: 43.3245, lng: 11.3289, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Siena, Italy", vibe: "City Historic", price: "$$", website: "https://www.albergominerva.it", desc: "AIC Certified.", badges: ["AIC Certified", "City"], verified: true },
    { id: 38, name: "Hotel Corallo", lat: 44.0678, lng: 12.5786, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Rimini, Italy", vibe: "Beach", price: "$", website: "https://www.hotelcorallorimini.com", desc: "AIC Certified.", badges: ["AIC Certified", "Beach"], verified: true },
    { id: 39, name: "Hotel Gambrinus", lat: 45.6793, lng: 13.1166, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Lignano, Italy", vibe: "Beach Family", price: "$$", website: "https://www.hotelgambrinus.com", desc: "AIC Certified.", badges: ["AIC Certified", "Family"], verified: true },
    { id: 40, name: "Hotel Carlton", lat: 42.4740, lng: 14.2127, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Pescara, Italy", vibe: "City / Beach", price: "$$", website: "https://www.carltonpescara.it", desc: "AIC Certified.", badges: ["AIC Certified", "City"], verified: true },
    { id: 41, name: "Hotel Mediterraneo", lat: 44.0044, lng: 12.6568, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Riccione, Italy", vibe: "Clubbing / Beach", price: "$$", website: "https://www.mediterraneoriccione.com", desc: "AIC Certified.", badges: ["AIC Certified", "Clubbing"], verified: true },
    { id: 42, name: "Hotel Continental", lat: 45.5694, lng: 10.7138, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Garda, Italy", vibe: "Lake Garda", price: "$$", website: "https://www.hotelcontinentalgarda.it", desc: "AIC Certified.", badges: ["AIC Certified", "Lake"], verified: true },
    { id: 43, name: "Hotel Caesius Thermae", lat: 45.5395, lng: 10.7303, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Bardolino, Italy", vibe: "Thermal Spa", price: "$$$", website: "https://www.hotelcaesius.com", desc: "AIC Certified.", badges: ["AIC Certified", "Spa"], verified: true },
    { id: 44, name: "Servigroup Venus", lat: 38.5394, lng: -0.1162, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Benidorm, Spain", vibe: "Resort", price: "$", website: "https://www.servigroup.com", desc: "FACE Agreement; dedicated GF zones.", badges: ["FACE Agreement", "Value"], verified: true },
    { id: 45, name: "Servigroup Galua", lat: 37.6433, lng: -0.7169, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "La Manga, Spain", vibe: "Beach", price: "$", website: "https://www.servigroup.com", desc: "FACE Agreement; dedicated GF zones.", badges: ["FACE Agreement", "Beach"], verified: true },
    { id: 46, name: "Indigo at One Aldwych", lat: 51.5117, lng: -0.1181, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "London, UK", vibe: "City Luxury", price: "$$$", website: "https://www.onealdwych.com", desc: "Restaurant is 100% GF/DF accredited.", badges: ["Accredited", "City"], verified: true },
    { id: 47, name: "Cannelle et Vanille Retreats", lat: 47.6062, lng: -122.3321, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Seattle, USA", vibe: "Educational / Foodie", price: "$$$", website: "https://www.cannelleetvanille.com", desc: "Strictly GF culinary workshops.", badges: ["Workshops", "Foodie"], verified: false },
    { id: 48, name: "Celiac Cruise", lat: 15.0, lng: -75.0, safetyClass: "Type 1", safetyLabel: "The Bubble", location: "Caribbean Sea", vibe: "Cruise", price: "$$", website: "https://www.celiaccruise.com", desc: "Chartered ships with scrubbed galleys.", badges: ["Chartered", "100% GF"], verified: false },
    { id: 49, name: "The Royal at Atlantis", lat: 25.0854, lng: -77.3204, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "Nassau, Bahamas", vibe: "Mega-Resort", price: "$$$", website: "https://www.atlantisbahamas.com", desc: "Chef's Office protocol; dedicated foil/pans.", badges: ["Protocol", "Mega-Resort"], verified: false },
    { id: 50, name: "Ritz-Carlton Central Park", lat: 40.7635, lng: -73.9749, safetyClass: "Type 2", safetyLabel: "Fort Knox", location: "New York, USA", vibe: "Ultra-Luxury", price: "$$$$", website: "https://www.ritzcarlton.com", desc: "Corporate allergy protocol (verify location).", badges: ["Corporate Protocol", "Luxury"], verified: false }
];

// Add images to each restaurant
restaurants.forEach(r => r.image = getRestaurantImage(r.vibe + ' ' + r.location));
